In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Admin\Downloads\logistics_delivery_dataset.csv")

In [8]:
df.head()

,Order_ID,Order_Date,Ship_Date,Delivery_Date,City,Region,Warehouse,Product_Category,Shipping_Mode,Distance_km,Shipping_Cost,Order_Value,delivery_days
0,O10000,2023-11-24,2023-11-25,2023-11-28,Chennai,North,W3,Clothing,Standard,1558,874.0,3956,3
1,O10001,2023-01-17,2023-01-18,2023-01-21,Hyderabad,North,W1,Beauty,Standard,1199,688.5,3936,3
2,O10002,2023-04-23,2023-04-25,2023-04-28,Bangalore,East,W1,Sports,Standard,368,247.0,1337,3
3,O10003,2023-02-17,2023-02-19,2023-02-24,Pune,North,W2,Beauty,Standard,138,157.0,1522,5
4,O10004,2023-07-13,2023-07-14,2023-07-17,Pune,East,W3,Beauty,Standard,192,153.0,1153,3

In [4]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Ship_Date"] = pd.to_datetime(df["Ship_Date"])
df["Delivery_Date"] = pd.to_datetime(df["Delivery_Date"])

In [6]:
df["delivery_days"] = (df["Delivery_Date"] - df["Ship_Date"]).dt.days

In [7]:
df.groupby("Region")["delivery_days"].mean()

Region
East     3.679308
North    3.672920
South    3.663766
West     5.255975
Name: delivery_days, dtype: float64

In [12]:
df.groupby("Warehouse")["delivery_days"].mean()

Warehouse
W1    3.566004
W2    3.597852
W3    5.085886
Name: delivery_days, dtype: float64

In [13]:
df.groupby("Shipping_Mode")["delivery_days"].mean()

Shipping_Mode
Express     3.392144
Standard    4.393966
Name: delivery_days, dtype: float64

In [14]:
df[["delivery_days","Distance_km","Shipping_Cost"]].corr()

               delivery_days  Distance_km  Shipping_Cost
delivery_days       1.000000     0.003106       0.005477
Distance_km         0.003106     1.000000       0.996590
Shipping_Cost       0.005477     0.996590       1.000000